CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Url" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NOT NULL,
    "Code" text NOT NULL,
    CONSTRAINT "PK_Url" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Url_Code" ON "Url" ("Code");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220205101932_InitialCreate', '6.0.1');

COMMIT;

